powerdata<- read.csv("C:/Users/Aishwarya/Documents/Data Science Specialization John hopkins/Exploratory data Analytics/Week 1/Assignment/ExData_Plotting1/household_power_consumption.txt",header=TRUE, sep=";",stringsAsFactors = FALSE)
powerdata$Date<-as.Date(powerdata$Date , format="%d/%m/%Y")
powerdata <- subset(powerdata, Date %in% as.Date(c("01/02/2007","02/02/2007"),"%d/%m/%Y"))
powerdata$Time <- format(powerdata$Time, format="%H:%M:%S")
powerdata$Global_active_power <- as.numeric(powerdata$Global_active_power)
powerdata$Global_reactive_power <- as.numeric(powerdata$Global_reactive_power)
powerdata$Voltage <- as.numeric(powerdata$Voltage)
powerdata$Global_intensity <- as.numeric(powerdata$Global_intensity)
powerdata$Sub_metering_1 <- as.numeric(powerdata$Sub_metering_1)
powerdata$Sub_metering_2 <- as.numeric(powerdata$Sub_metering_2)
powerdata$Sub_metering_3 <- as.numeric(powerdata$Sub_metering_3)
png(filename="plot1.png",width=480,height = 480)
hist(powerdata$Global_active_power,col="red",main = "Global Active Power",xlab = "Global Active Power (kilowatts)",ylab = "Frequency",border = "black")
dev.off()